#================================================================================
# dust config file
#================================================================================
#options: cardelli, calzetti
dust_curve: "calzetti"
#...............................................................................
# H Beta
wave_H_beta: 4861
flux_H_beta: 100
#..............................................................................
#other
wave_other: 6563
flux_other: 465.402
#...............................................................................
intrinsic_ratio: 2.87378
